#!/usr/bin/env python3
"""Generate docker compose mount variables from config/config.yml."""

from __future__ import annotations

from pathlib import Path
import re
import sys


ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = ROOT / "config" / "config.yml"
OUTPUT_PATH = Path(__file__).resolve().parent / ".env.compose"

KEYS = ("data_dir", "models_dir", "reports_dir", "docker_group_id", "jupyter_host", "jupyter_port")
LINE_RE = re.compile(r"^(?P<key>[a-zA-Z0-9_]+)\s*:\s*(?P<value>.+?)\s*$")


def _parse_value(raw_value: str) -> str:
    value = raw_value.split(" #", 1)[0].strip()
    if (value.startswith('"') and value.endswith('"')) or (
        value.startswith("'") and value.endswith("'")
    ):
        value = value[1:-1]
    return value


def _read_config_keys(config_text: str) -> dict[str, str]:
    values: dict[str, str] = {}

    for line in config_text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if line.startswith((" ", "\t")):
            continue

        match = LINE_RE.match(stripped)
        if not match:
            continue

        key = match.group("key")
        if key not in KEYS:
            continue

        values[key] = _parse_value(match.group("value"))

    missing = [key for key in KEYS if key not in values]
    if missing:
        raise ValueError(f"Missing keys in {CONFIG_PATH}: {', '.join(missing)}")

    return values


def _to_mount(path_value: str) -> str:
    source = f"../{path_value.lstrip('./')}"
    target = f"/app/{path_value.lstrip('./')}"
    return f"{source}:{target}"


def main() -> int:
    if not CONFIG_PATH.exists():
        print(f"Config not found: {CONFIG_PATH}", file=sys.stderr)
        return 1

    try:
        config_values = _read_config_keys(CONFIG_PATH.read_text(encoding="utf-8"))
    except ValueError as err:
        print(str(err), file=sys.stderr)
        return 1

    lines = [
        "# Auto-generated by docker/generate_compose_env.py",
        f"FERDINAND_DATA_MOUNT={_to_mount(config_values['data_dir'])}",
        f"FERDINAND_MODELS_MOUNT={_to_mount(config_values['models_dir'])}",
        f"FERDINAND_REPORTS_MOUNT={_to_mount(config_values['reports_dir'])}",
        f"FERDINAND_GROUP_ID={config_values['docker_group_id']}",
        f"FERDINAND_JUPYTER_HOST={config_values['jupyter_host']}",
        f"FERDINAND_JUPYTER_PORT={config_values['jupyter_port']}",
        "",
    ]
    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")

    print(f"Wrote {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
