# GLOBAL CONFIGURATION FILE - imported by all jupyter notebooks
# ==============================================================

# Settings related to the dataset creation pipeline run, 
# including the name and description of the run, the data source, and the IMPC centers to be included in the dataset.
run_mode: &run_mode "REAL"  # Options: REAL=download everything, TEST=only 20 rows
run_name: &run_name "DR23_2025-09-23"  # A name for the dataset creation pipeline run, to be used in the directory structure of the dataset and in the reports.
run_description: &run_description "Dataset creation pipeline run for the DR23 release of the IMPC radiographs"
data_source: &data_source "IMPC"

# List of IMPC centers to be included in the dataset
centers:
  - WTSI
  - JAX
  - MRC Harwell
  - UC Davis
  - HMGU
  - CCP-IMG
  - TCP
  - BCM
  - ICS
  - RBRC
  - KMPC
  - MARC

# List of columns to be fetched from the API and stored in the SQLite database, related to the mouse metadata.
mouse_columns:
  - center
  - mouse_id
  - strain
  - dob
  - sex
  - cohort_type
  - gene_symbol

# Additional fields to be fetched from the API and stored in the SQLite database, 
# related to the images and their metadata, that are not included in the api_fields list defined in the code.
additional_api_fields:

# List of parameters defining the images to be included in the dataset, 
# including the stable ID of the procedure, a description of the image type, the due week for the procedure, 
# and a name for the work (procedure) to be used in the directory structure of the dataset.
parameters:
  - stable_id: "IMPC_XRY_034_001"
    description: "whole body X-Ray dorso-ventral"
    week: "14"
    work_name: "xray_dv"

# This parameter defines the maximum allowed deviation in weeks from the due week for including images in the dataset. 
# For example, if the due week is 14 and the max_pipeline_deviation is set to 5, 
# then images taken between weeks 9 and 19 (inclusive) will be included in the dataset, 
# while images taken outside of this range will be excluded.
max_pipeline_deviation: 5

# The project root directory, which is the parent directory of the directories for storing 
# data, reports, models, and the sqlite database.
project_root: ".."

# Directory for storing all data related to the dataset, including raw data, preprocessed data, and the sqlite database.
data_dir: "data"
# Definition of the subdirectories within the data_dir directory for storing different types of data,
data_directories:
  all_data_dir: "000_all_data"
  raw_data_dir: "100_raw_data"
  center_data_dir: "110_center_data"
  images_dir: "200_all_images"
  thumbnails_dir: "210_all_thumbnails"
  preprocessed_dir: "300_preprocessed_images"
  preprocessed_thumbnails_dir: "310_preprocessed_thumbnails"
  rotated_dir: "400_rotated_images"
  rotated_thumbnails_dir: "410_rotated_thumbnails"

# Directory for storing all reports related to the dataset creation pipeline, 
# including quality control reports and orientation angle prediction reports.
reports_dir: "reports"

# Directory for storing all models related to the dataset creation pipeline, 
# including the angle detection model used for predicting the orientation angle of images in the dataset.
models_dir: "models"
# Angle detection model trained on a subset of the data, to be used for predicting the orientation angle of images in the dataset
angle_detection_model: "2026-02-09_rotation_cnn_model.h5"

# Name of the sqlite database file (without the .db extension) to be created in the all_data_dir directory, 
# and used for storing all metadata related to the images in the dataset 
# and the results of the quality control and orientation angle prediction steps
sqlite_db: "IMPC_radiographs"

# Settings summary
settings:
  run_mode: *run_mode
  run_name: *run_name
  run_description: *run_description
  data_source: *data_source